CREATE TABLE products (
  id INT NOT NULL AUTO_INCREMENT,
  sku VARCHAR(60) NOT NULL,
  is_dispatchable BOOLEAN NOT NULL,
  amount INT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP NOT NULL DEFAULT NOW(),
  PRIMARY KEY (id),
  UNIQUE KEY (sku)
);
