CREATE TABLE products (
  id INT NOT NULL,
  sku VARCHAR(60) NOT NULL,
  is_dispatchable BOOLEAN NOT NULL,
  amount INT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP NOT NULL DEFAULT NOW(),
  PRIMARY KEY (id)
);

CREATE SEQUENCE products_seq
  START WITH 1
  INCREMENT BY 1
  MINVALUE 1;
