
server.port: 8081

spring.datasource:
  url: jdbc:mysql://localhost:3306/camunda?autoReconnect=true&sendFractionalSeconds=false
  username: camunda
  password: camunda

itau:
  components:
    camunda-external-task:
      connection:
        base-url: "http://localhost:8080"
        lock-duration: 30s
        async-timeout: 2s
        max-retries: 1
