server.port: 8081

spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate.ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        enable_lazy_load_no_trans: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/order?autoReconnect=true&sendFractionalSeconds=false
    username: order
    password: order

  flyway:
    enabled: true
    locations: classpath:db/migrations/schema

itau:
  components:
    camunda-external-task:
      connection:
        base-url: "http://localhost:8080"
        lock-duration: 30s
        async-timeout: 2s
        max-retries: 1
